spring:
  datasource:
    url: jdbc:oracle:thin:@115.90.212.18:10000:XE
    username: C##MP
    password: 1234
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari:
      maximum-pool-size: 30
      connection-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true